import LeanMiniscript.Extraction.TaprootExamples
import LeanMiniscript.Bitcoin.TaprootControlBlockExamples
import LeanMiniscript.Script.SchnorrExecutionExamples
import LeanMiniscript.Bitcoin.SchnorrExamples
import LeanMiniscript
import LeanMiniscript.Bitcoin.TaprootSighashExamples
import LeanMiniscript.Extraction.BitcoinCoreAuditExamples
import LeanMiniscript.Extraction.BitcoinCoreFixturesExamples
import LeanMiniscript.Extraction.SignatureEncodingCoreExamples
import LeanMiniscript.Miniscript.CompileExamples
import LeanMiniscript.Miniscript.ContextSafetyExamples
import LeanMiniscript.Miniscript.MalleabilityExamples
import LeanMiniscript.Miniscript.SaneExamples
import LeanMiniscript.Miniscript.SatisfactionAvailabilityExamples
import LeanMiniscript.Miniscript.SatisfactionExamples
import LeanMiniscript.Miniscript.SurfaceTextExamples
import LeanMiniscript.Miniscript.SurfaceTextRoundTripExamples
import LeanMiniscript.Miniscript.TimelockMixingExamples
import LeanMiniscript.Miniscript.TypeInferenceExamples
import LeanMiniscript.Properties.ResourceBoundsExamples
import LeanMiniscript.Script.BigStepFailureExamples
import LeanMiniscript.Script.CheckMultiSigExamples
import LeanMiniscript.Script.ConditionalExamples
import LeanMiniscript.Script.EvaluatorExamples
import LeanMiniscript.Script.ExecutionResourcesExamples
import LeanMiniscript.Script.NullFailExamples
import LeanMiniscript.Script.ScriptNumExamples
import LeanMiniscript.Script.SignatureEncodingExamples
import LeanMiniscript.Script.SighashExecutionExamples
import LeanMiniscript.Script.SignatureVersionExamples
import LeanMiniscript.Script.SerializationExamples
import LeanMiniscript.Script.ValidationWeightExamples
import LeanMiniscript.Script.TapscriptAcceptanceExamples
import LeanMiniscript.Script.TapscriptWitnessPolicyExamples
import LeanMiniscript.Script.RuntimeLimitsExamples
import LeanMiniscript.Script.TimelockExamples

/-! Build-checked external conformance, executable boundary, and semantic
regression fixtures. General theorem applications belong in
`LeanMiniscript.Proofs` and are not duplicated here. -/
