import LeanMiniscript
import LeanMiniscript.Miniscript.CompileExamples
import LeanMiniscript.Miniscript.ContextSafetyExamples
import LeanMiniscript.Miniscript.MalleabilityExamples
import LeanMiniscript.Miniscript.SurfaceTextExamples
import LeanMiniscript.Miniscript.SurfaceTextRoundTripExamples
import LeanMiniscript.Miniscript.TimelockMixingExamples
import LeanMiniscript.Miniscript.TypeInferenceExamples
import LeanMiniscript.Script.BigStepFailureExamples
import LeanMiniscript.Script.CheckMultiSigExamples
import LeanMiniscript.Script.ScriptNumExamples
import LeanMiniscript.Script.SerializationExamples

/-! Build-checked fixtures and regression examples for lean-miniscript. -/
