import LeanMiniscript.Bitcoin.ECDSA

namespace LeanMiniscript.Bitcoin.ECDSA

private def digit (byte : UInt8) : Nat :=
  if byte.toNat ≤ 57 then byte.toNat - 48 else byte.toNat - 87
private def decodeHex : List UInt8 → List UInt8
  | a :: b :: rest => UInt8.ofNat (16 * digit a + digit b) :: decodeHex rest
  | _ => []
private def hex (text : String) : ByteArray := ⟨(decodeHex text.toUTF8.data.toList).toArray⟩

-- BEGIN GENERATED VECTORS
/-! Official BIP143 SHA-256: 62bc71351563e68baeb12643c68355d217953ae9eb6a6e68b2b0323275b6beec.
Thirteen published ECDSA signatures, excluding their Script hash-type bytes.
Derived cases cover uncompressed/hybrid keys, high S, ignored sequence lengths,
trailing bytes, long descriptors and excessive scalar padding.
Generated by scripts/generate_ecdsa_fixtures.py. -/
private def bip143Signatures : Array (String × String × String) := #[
  ("304402203609e17b84f6a7d30c80bfa610b5b4542f32a8a0d5447a12fb1366d7f01cc44a0220573a954c4518331561406f90300e8f3358f51928d43c212a8caed02de67eebee", "025476c2e83188368da1ff3e292e7acafcdb3566bb0ad253f62fc70f07aeee6357", "c37af31116d1b27caf68aae9e3ac82f1477929014d5b917657d0eb49478cb670"),
  ("3044022047ac8e878352d3ebbde1c94ce3a10d057c24175747116f8288e5d794d12d482f0220217f36a485cae903c713331d877c1f64677e3622ad4010726870540656fe9dcb", "03ad1d8e89212f0b92c74d23bb710c00662ad1470198ac48c43f7d6f93a2a26873", "64f3b0f4dd2bb3aa1ce8566d220cc74dda9df97d8490cc81d89d735c92e59fb6"),
  ("3044022027dc95ad6b740fe5129e7e62a75dd00f291a2aeb1200b84b09d9e3789406b6c002201a9ecd315dd6a0e632ab20bbb98948bc0c6fb204f2c286963bb48517a7058e27", "026dccc749adc2a9d0d89497ac511f760f45c47dc5ed9cf352a58ac706453880ae", "82dde6e4f1e94d02c2b7ad03d2115d691f48d064e9d52f58194a6637e4194391"),
  ("304402200de66acf4527789bfda55fc5459e214fa6083f936b430a762c629656216805ac0220396f550692cd347171cbc1ef1f51e15282e837bb2b30860dc77c8f78bc8501e5", "0255a9626aebf5e29c0e6538428ba0d1dcf6ca98ffdf086aa8ced5e0d0215ea465", "fef7bd749cce710c5c052bd796df1af0d935e59cea63736268bcbe2d2134fc47"),
  ("3045022100f6a10b8604e6dc910194b79ccfc93e1bc0ec7c03453caaa8987f7d6c3413566002206216229ede9b4d6ec2d325be245c5b508ff0339bf1794078e20bfe0babc7ffe6", "0392972e2eb617b2388771abe27235fd5ac44af8e61693261550447a4c3e39da98", "e9071e75e25b8a1e298a72f0d2e9f4f95a0f5cdf86a533cda597eb402ed13b3a"),
  ("30440220032521802a76ad7bf74d0e2c218b72cf0cbc867066e2e53db905ba37f130397e02207709e2188ed7f08f4c952d9d13986da504502b8c3be59617e043552f506c46ff", "0392972e2eb617b2388771abe27235fd5ac44af8e61693261550447a4c3e39da98", "cd72f1f1a433ee9df816857fad88d8ebd97e09a75cd481583eb841c330275e54"),
  ("304402206ac44d672dac41f9b00e28f4df20c52eeb087207e8d758d76d92c6fab3b73e2b0220367750dbbe19290069cba53d096f44530e4f98acaa594810388cf7409a1870ce", "0307b8ae49ac90a048e9b53357a2354b3334e9c8bee813ecb98e99a7e07e8c3ba3", "185c0be5263dce5b4bb50a047973c1b6272bfbd0103a89444597dc40b248ee7c"),
  ("3044022068c7946a43232757cbdf9176f009a928e1cd9a1a8c212f15c1e11ac9f2925d9002205b75f937ff2f9f3c1246e547e54f62e027f64eefa2695578cc6432cdabce2715", "03b28f0c28bfab54554ae8c658ac5c3e0ce6e79ad336331f78c428dd43eea8449b", "e9733bc60ea13c95c6527066bb975a2ff29a925e80aa14c213f686cbae5d2f36"),
  ("3044022059ebf56d98010a932cf8ecfec54c48e6139ed6adb0728c09cbe1e4fa0915302e022007cd986c8fa870ff5d2b3a89139c9fe7e499259875357e20fcbb15571c767954", "034b8113d703413d57761b8b9781957b8c0ac1dfe69f492580ca4195f50376ba4a", "1e1f1c303dc025bd664acb72e583e933fae4cff9148bf78c157d1e8f78530aea"),
  ("3045022100fbefd94bd0a488d50b79102b5dad4ab6ced30c4069f1eaa69a4b5a763414067e02203156c6a5c9cf88f91265f5a942e96213afae16d83321c8b31bb342142a14d163", "033400f6afecb833092a9a21cfdf1ed1376e58c5d1f47de74683123987e967a8f4", "2a67f03e63a6a422125878b40b82da593be8d4efaafe88ee528af6e5a9955c6e"),
  ("3045022100a5263ea0553ba89221984bd7f0b13613db16e7a70c549a86de0cc0444141a407022005c360ef0ae5a5d4f9f2f87a56c1546cc8268cab08c73501d6b3be2e1e1a8a08", "03a6d48b1131e94ba04d9737d61acdaa1322008af9602b3b14862c07a1789aac16", "781ba15f3779d5542ce8ecb5c18716733a5ee42a6f51488ec96154934e2c890a"),
  ("30440220525406a1482936d5a21888260dc165497a90a15669636d8edca6b9fe490d309c022032af0c646a34a44d1f4576bf6a4a74b67940f8faa84c7df9abe12a01a11e2b47", "02d8b661b0b3302ee2f162b09e07a55ad5dfbe673a9f01d9f0c19617681024306b", "511e8e52ed574121fc1b654970395502128263f62662e076dc6baf05c2e6a99b"),
  ("30450220487fb382c4974de3f7d834c1b617fe15860828c7f96454490edd6d891556dcc9022100baf95feb48f845d5bfc9882eb6aeefa1bc3790e39f59eaa46ff7f15ae626c53e", "02a9781d66b61fb5a7ef00ac5ad5bc6ffc78be7b44a566e3c87870e1079368df4c", "71c9cd9b2869b9c70b01b1f0360c148f42dee72297db312638df136f43311f23")]
private def compatibilitySignatures : Array (String × String × String) := #[
  ("304402203609e17b84f6a7d30c80bfa610b5b4542f32a8a0d5447a12fb1366d7f01cc44a0220573a954c4518331561406f90300e8f3358f51928d43c212a8caed02de67eebee", "045476c2e83188368da1ff3e292e7acafcdb3566bb0ad253f62fc70f07aeee6357fd57dee6b46a6b010a3e4a70961ecf44a40e18b279ec9e9fba9c1dbc64896198", "c37af31116d1b27caf68aae9e3ac82f1477929014d5b917657d0eb49478cb670"),
  ("304402203609e17b84f6a7d30c80bfa610b5b4542f32a8a0d5447a12fb1366d7f01cc44a0220573a954c4518331561406f90300e8f3358f51928d43c212a8caed02de67eebee", "065476c2e83188368da1ff3e292e7acafcdb3566bb0ad253f62fc70f07aeee6357fd57dee6b46a6b010a3e4a70961ecf44a40e18b279ec9e9fba9c1dbc64896198", "c37af31116d1b27caf68aae9e3ac82f1477929014d5b917657d0eb49478cb670"),
  ("304502203609e17b84f6a7d30c80bfa610b5b4542f32a8a0d5447a12fb1366d7f01cc44a022100a8c56ab3bae7ccea9ebf906fcff170cb61b9c3bddb0c7f1133238e5ee9b75553", "025476c2e83188368da1ff3e292e7acafcdb3566bb0ad253f62fc70f07aeee6357", "c37af31116d1b27caf68aae9e3ac82f1477929014d5b917657d0eb49478cb670"),
  ("300002203609e17b84f6a7d30c80bfa610b5b4542f32a8a0d5447a12fb1366d7f01cc44a0220573a954c4518331561406f90300e8f3358f51928d43c212a8caed02de67eebeeff01", "025476c2e83188368da1ff3e292e7acafcdb3566bb0ad253f62fc70f07aeee6357", "c37af31116d1b27caf68aae9e3ac82f1477929014d5b917657d0eb49478cb670"),
  ("3083ffffff02203609e17b84f6a7d30c80bfa610b5b4542f32a8a0d5447a12fb1366d7f01cc44a0220573a954c4518331561406f90300e8f3358f51928d43c212a8caed02de67eebee", "025476c2e83188368da1ff3e292e7acafcdb3566bb0ad253f62fc70f07aeee6357", "c37af31116d1b27caf68aae9e3ac82f1477929014d5b917657d0eb49478cb670"),
  ("30000284000000203609e17b84f6a7d30c80bfa610b5b4542f32a8a0d5447a12fb1366d7f01cc44a0283000020573a954c4518331561406f90300e8f3358f51928d43c212a8caed02de67eebee", "025476c2e83188368da1ff3e292e7acafcdb3566bb0ad253f62fc70f07aeee6357", "c37af31116d1b27caf68aae9e3ac82f1477929014d5b917657d0eb49478cb670"),
  ("3000022200003609e17b84f6a7d30c80bfa610b5b4542f32a8a0d5447a12fb1366d7f01cc44a02220000573a954c4518331561406f90300e8f3358f51928d43c212a8caed02de67eebee", "025476c2e83188368da1ff3e292e7acafcdb3566bb0ad253f62fc70f07aeee6357", "c37af31116d1b27caf68aae9e3ac82f1477929014d5b917657d0eb49478cb670")]
-- END GENERATED VECTORS

example : bip143Signatures.size = 13 := by native_decide
example : bip143Signatures.all (fun (sig, key, digest) =>
    verify (hex sig) (hex key) (hex digest)) = true := by native_decide
example : compatibilitySignatures.all (fun (sig, key, digest) =>
    verify (hex sig) (hex key) (hex digest)) = true := by native_decide

private def original : String × String × String := bip143Signatures[0]!
private def originalSig : ByteArray := hex original.1
private def originalKey : ByteArray := hex original.2.1
private def originalDigest : ByteArray := hex original.2.2

-- Correct signatures must bind both the supplied message and public key.
example : verify originalSig originalKey (⟨(List.replicate 32 0).toArray⟩) = false := by native_decide
example : verify originalSig (hex bip143Signatures[1]!.2.1) originalDigest = false := by native_decide
example : verify originalSig originalKey (originalDigest.extract 0 31) = false := by native_decide
example : verify originalSig originalKey (originalDigest.push 0) = false := by native_decide
example : verify (hex "3006020100020101") originalKey originalDigest = false := by native_decide
example : verify (hex "3006020101020100") originalKey originalDigest = false := by native_decide

-- The R/S parser follows Core's lax parser independently of Script DERSIG.
example : parseLaxDER (hex "3006020180020181") = some (128, 129) := by native_decide
example : parseLaxDER (hex "3000020101020102ffff") = some (1, 2) := by native_decide
example : parseLaxDER (hex "3080020101020102") = some (1, 2) := by native_decide
example : parseLaxDER (hex "3083010203020101020102") = some (1, 2) := by native_decide
example : parseLaxDER (hex "300002840000000101028300000102") = some (1, 2) := by native_decide
example : parseLaxDER (hex "300002000200") = some (0, 0) := by native_decide
example : parseLaxDER (hex "300002800280") = some (0, 0) := by native_decide
example : parseLaxDER (hex "3000020300000102020002") = some (1, 2) := by native_decide
example : parseLaxDER (hex "30000220fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141020101") =
    some (0, 0) := by native_decide
example : parseLaxDER (hex "30000221010000000000000000000000000000000000000000000000000000000000000000020101") =
    some (0, 0) := by native_decide
private def malformedDER : Array String := #[
  "", "30", "3106020101020101", "3084", "3000030101020101", "300002", "3000028201",
  "300002840100000001020101", "3000020201", "3000020101030101", "300002010102",
  "30000201010202", "300002010102840100000001"]
example : malformedDER.all (fun value => (parseLaxDER (hex value)).isNone) = true := by native_decide

-- Off-curve, out-of-field, invalid prefix, and inconsistent hybrid parity.
private def malformedKeys : Array String := #[
  "", "02", "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179",
  "0479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
  "02fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f",
  "020000000000000000000000000000000000000000000000000000000000000000",
  "0479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b9",
  "0479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f",
  "0779be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8",
  "0579be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8"]
example : malformedKeys.all (fun value => (parsePublicKey (hex value)).isNone) = true := by native_decide
example : malformedKeys.all (fun value => !verify originalSig (hex value) originalDigest) = true := by native_decide

-- r=1, s=1, z=n-1 and Q=G produce the point at infinity.
example : verify (hex "3006020101020101")
    (hex "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798")
    (hex "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140") = false := by native_decide

end LeanMiniscript.Bitcoin.ECDSA
