import LeanMiniscript.Extraction.CoreFixtureTransaction
import LeanMiniscript.Bitcoin.ECDSA

namespace LeanMiniscript.Extraction

open Bitcoin

private def digit (byte : UInt8) : Nat :=
  if byte.toNat ≤ 57 then byte.toNat - 48 else byte.toNat - 87
private def decodeHex : List UInt8 → List UInt8
  | a :: b :: rest => UInt8.ofNat (16 * digit a + digit b) :: decodeHex rest
  | _ => []
private def hex (text : String) : ByteArray := ⟨(decodeHex text.toUTF8.data.toList).toArray⟩

-- BEGIN GENERATED VECTORS
/-! Core revision 9be056a8a72b624dae9623b2f7bded92c2a21c91, script_tests.json.
Source SHA-256: bc23cb1dfa760d50042f534da23cbbe4b6fbb03d7def0b64f8de049453d6ead5.
Indices below include upstream comment rows; expected values concern CHECKSIG
before an optional NOT. Strict Script encoding flags remain outside this test.
Generated by scripts/generate_core_fixture_transaction_examples.py. -/
private def coreSignatures : Array (String × String × Bool) := #[
  -- Upstream row 1028: P2PK.
  ("47304402200a5c6163f07b8d3b013c4d1d6dba25e780b39658d79ba37af7057a3b7f15ffa102201fd9b4eaa9943f734928b99a83592c2e7bf342ea2680f6a2bb705167966b742001", "410479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8ac", true),
  -- Upstream row 1029: P2PK, bad sig.
  ("47304402200a5c6163f07b8c3b013c4d1d6dba25e780b39658d79ba37af7057a3b7f15ffa102201fd9b4eaa9943f734928b99a83592c2e7bf342ea2680f6a2bb705167966b742001", "410479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8ac", false),
  -- Upstream row 1032: P2PK anyonecanpay.
  ("47304402204710a85181663b32d25c70ec2bbd14adff5ddfff6cb50d09e155ef5f541fc86c0220056b0cc949be9386ecc5f6c2ac0493269031dbb185781db90171b54ac127790281", "41048282263212c609d9ea2a6e3e172de238d8c39cabd5ac1ca10646e23fd5f5150811f8a8098557dfe45e8256e830b60ace62d613ac2f7b17bed31b6eaff6e26cafac", true),
  -- Upstream row 1033: P2PK anyonecanpay marked with normal hashtype.
  ("47304402204710a85181663b32d25c70ec2bbd14adff5ddfff6cb50d09e155ef5f541fc86c0220056b0cc949be9386ecc5f6c2ac0493269031dbb185781db90171b54ac127790201", "41048282263212c609d9ea2a6e3e172de238d8c39cabd5ac1ca10646e23fd5f5150811f8a8098557dfe45e8256e830b60ace62d613ac2f7b17bed31b6eaff6e26cafac", false),
  -- Upstream row 1043: P2PK with too much R padding but no DERSIG.
  ("47304402200060558477337b9022e70534f1fea71a318caf836812465a2509931c5e7c4987022078ec32bd50ac9e03a349ba953dfd9fe1c8d2dd8bdb1d38ddca844d3d5c78c11801", "21038282263212c609d9ea2a6e3e172de238d8c39cabd5ac1ca10646e23fd5f51508ac", true),
  -- Upstream row 1045: P2PK with too much S padding but no DERSIG.
  ("48304502202de8c03fc525285c9c535631019a5f2af7c6454fa9eb392a3756a4917c420edd02210046130bf2baf7cfc065067c8b9e33a066d9c15edcea9feb0ca2d233e3597925b401", "21038282263212c609d9ea2a6e3e172de238d8c39cabd5ac1ca10646e23fd5f51508ac", true),
  -- Upstream row 1047: P2PK with too little R padding but no DERSIG.
  ("4730440220d7a0417c3f6d1a15094d1cf2a3378ca0503eb8a57630953a9e2987e21ddd0a6502207a6266d686c99090920249991d3d42065b6d43eb70187b219c0db82e4f94d1a201", "21038282263212c609d9ea2a6e3e172de238d8c39cabd5ac1ca10646e23fd5f51508ac", true),
  -- Upstream row 1049: P2PK NOT with bad sig with too much R padding but no DERSIG.
  ("4730440220005ece1335e7f757a1a1f476a7fb5bd90964e8a022489f890614a04acfb734c002206c12b8294a6513c7710e8c82d3c23d75cdbfe83200eb7efb495701958501a5d601", "2103363d90d447b00c9c99ceac05b6262ee053441c7e55552ffe526bad8f83ff4640ac91", false),
  -- Upstream row 1080: P2PK with multi-byte hashtype, without DERSIG.
  ("48304402203e4516da7253cf068effec6b95c41221c0cf3a8e6ccb8cbf1725b562e9afde2c022054e1c258c2981cdfba5df1f46661fb6541c44f77ca0092f3600331abfffb12510101", "2103363d90d447b00c9c99ceac05b6262ee053441c7e55552ffe526bad8f83ff4640ac", true),
  -- Upstream row 1082: P2PK with high S but no LOW_S.
  ("48304502203e4516da7253cf068effec6b95c41221c0cf3a8e6ccb8cbf1725b562e9afde2c022100ab1e3da73d67e32045a20e0b999e049978ea8d6ee5480d485fcf2ce0d03b2ef001", "2103363d90d447b00c9c99ceac05b6262ee053441c7e55552ffe526bad8f83ff4640ac", true),
  -- Upstream row 1084: P2PK with hybrid pubkey but no STRICTENC.
  ("473044022057292e2d4dfe775becdd0a9e6547997c728cdf35390f6a017da56d654d374e4902206b643be2fc53763b4e284845bfea2c597d2dc7759941dce937636c9d341b71ed01", "410679be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8ac", true),
  -- Upstream row 1090: P2PK NOT with invalid hybrid pubkey but no STRICTENC.
  ("4730440220035d554e3153c04950c9993f41c496607a8e24093db0595be7bf875cf64fcf1f02204731c8c4e5daf15e706cec19cdd8f2c5b1d05490e11dab8465ed426569b6e92101", "410679be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8ac91", false),
  -- Upstream row 1095: P2PK with undefined hashtype but no STRICTENC.
  ("47304402206177d513ec2cda444c021a1f4f656fc4c72ba108ae063e157eb86dc3575784940220666fc66702815d0e5413bb9b1df22aed44f5f1efb8b99d41dd5dc9a5be6d205205", "41048282263212c609d9ea2a6e3e172de238d8c39cabd5ac1ca10646e23fd5f5150811f8a8098557dfe45e8256e830b60ace62d613ac2f7b17bed31b6eaff6e26cafac", true),
  -- Upstream row 1097: P2PK NOT with invalid sig and undefined hashtype but no STRICTENC.
  ("47304402207409b5b320296e5e2136a7b281a7f803028ca4ca44e2b83eebd46932677725de02202d4eea1c8d3c98e6f42614f54764e6e5e6542e213eb4d079737e9a8b6e9812ec05", "41048282263212c609d9ea2a6e3e172de238d8c39cabd5ac1ca10646e23fd5f5150811f8a8098557dfe45e8256e830b60ace62d613ac2f7b17bed31b6eaff6e26cafac91", false)]
private def expectedCredit : String := "01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff020000ffffffff012a00000000000000015100000000"
private def expectedSpend : String := "0100000001efc6e7e27de4b759a05290cde91d942abed5ff587260e26e0d87173cf0f05c8b00000000020155ffffffff012a000000000000000000000000"
-- END GENERATED VECTORS

-- Every selected scriptSig is one direct push; every scriptPubKey is a direct
-- key push followed by CHECKSIG, optionally NOT. No FindAndDelete is required.
private def verifyFixtureSignature (sigText scriptText : String) : Bool :=
  let scriptSig := hex sigText
  let scriptPubKey := hex scriptText
  let signature := scriptSig.extract 1 scriptSig.size
  let key := scriptPubKey.extract 1 (1 + scriptPubKey[0]!.toNat)
  let fixture := coreFixtureTransaction scriptSig scriptPubKey 0
  match legacySignatureHash fixture.spend fixture.inputIndex scriptPubKey
      (UInt32.ofNat signature[signature.size - 1]!.toNat) with
  | .error _ => false
  | .ok digest => ECDSA.verify (signature.extract 0 (signature.size - 1)) key digest

example : coreSignatures.size = 14 := by native_decide
example : coreSignatures.all (fun (sig, script, expected) =>
    verifyFixtureSignature sig script == expected) = true := by native_decide

private def simpleFixture : CoreFixtureTransaction :=
  coreFixtureTransaction (hex "0155") (hex "51") 42
example : serializeTransaction simpleFixture.credit == hex expectedCredit := by native_decide
example : serializeTransaction simpleFixture.spend == hex expectedSpend := by native_decide
example : simpleFixture.amount = 42 ∧ simpleFixture.inputIndex = 0 ∧
    simpleFixture.spentOutputs.size = 1 ∧ simpleFixture.spentOutputs[0]!.amount = 42 := by
  native_decide

end LeanMiniscript.Extraction
