import LeanMiniscript.Miniscript.SatisfactionGeneratedProofs

namespace LeanMiniscript.Miniscript

open LeanMiniscript.Script

/-!
# Recursive generated-satisfaction contract

The constructor-local contracts compose by mutual recursion over `HasType` and
`HasTypeList`. The list theorem keeps threshold children and their candidate
pairs aligned in source order.
-/

mutual

/-- Every well-formed, well-typed core fragment has the strong contract for
    every usable witness generated by `satisfactionCandidates`. -/
theorem supportsGeneratedContract_of_wellFormed_hasType
    {scriptCtx : ScriptContext} {fragment : CoreFragment} {ty : MiniType}
    {env : SatEnv} {flags : ScriptFlags}
    (version : ModeledContextVersion scriptCtx env.txCtx)
    (modeled : ModeledContextFlags scriptCtx flags)
    (sound : env.Sound) (encodings : env.EncodingSound flags)
    (typed : HasType scriptCtx fragment ty)
    (wellFormed : CoreFragment.WellFormed scriptCtx fragment) :
    (satisfactionCandidates fragment env).SupportsGeneratedContract
      scriptCtx fragment ty flags env.txCtx := by
  cases typed with
  | zero => exact generatedContract_zero scriptCtx env flags
  | one => exact generatedContract_one scriptCtx env flags
  | pk_k key =>
      exact generatedContract_pk_k_of_modeled wellFormed version modeled sound
        encodings
  | pk_h key =>
      exact generatedContract_pk_h_of_modeled wellFormed version modeled sound
        encodings
  | older n => exact generatedContract_older wellFormed
  | after n => exact generatedContract_after wellFormed
  | sha256 hash =>
      simpa [HashLock.fragment, satisfactionCandidates] using
        (generatedContract_hash (scriptCtx := scriptCtx)
          (lock := HashLock.sha256 hash) (env := env) (flags := flags) sound)
  | hash256 hash =>
      simpa [HashLock.fragment, satisfactionCandidates] using
        (generatedContract_hash (scriptCtx := scriptCtx)
          (lock := HashLock.hash256 hash) (env := env) (flags := flags) sound)
  | ripemd160 hash =>
      simpa [HashLock.fragment, satisfactionCandidates] using
        (generatedContract_hash (scriptCtx := scriptCtx)
          (lock := HashLock.ripemd160 hash) (env := env) (flags := flags) sound)
  | hash160 hash =>
      simpa [HashLock.fragment, satisfactionCandidates] using
        (generatedContract_hash (scriptCtx := scriptCtx)
          (lock := HashLock.hash160 hash) (env := env) (flags := flags) sound)
  | @and_v first second firstMods secondType firstTyped secondTyped branch =>
      simp only [CoreFragment.WellFormed] at wellFormed
      have firstSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings firstTyped wellFormed.1
      have secondSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings secondTyped wellFormed.2.1
      simpa [satisfactionCandidates] using
        (CandidatePair.SupportsGeneratedContract.and_v firstSupported
          secondSupported branch)
  | @and_b first second firstMods secondMods firstTyped secondTyped =>
      simp only [CoreFragment.WellFormed] at wellFormed
      have firstSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings firstTyped wellFormed.1
      have secondSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings secondTyped wellFormed.2.1
      simpa [satisfactionCandidates] using
        (CandidatePair.SupportsGeneratedContract.and_b firstSupported secondSupported)
  | @or_b first second firstMods secondMods firstTyped firstD secondTyped secondD =>
      simp only [CoreFragment.WellFormed] at wellFormed
      have firstSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings firstTyped wellFormed.1
      have secondSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings secondTyped wellFormed.2
      simpa [satisfactionCandidates] using
        (CandidatePair.SupportsGeneratedContract.or_b firstSupported firstD
          secondSupported secondD)
  | @or_c first second firstMods secondMods firstTyped firstD firstUnit secondTyped =>
      simp only [CoreFragment.WellFormed] at wellFormed
      have firstSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings firstTyped wellFormed.1
      have secondSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings secondTyped wellFormed.2
      simpa [satisfactionCandidates] using
        (CandidatePair.SupportsGeneratedContract.or_c firstSupported firstD
          firstUnit secondSupported)
  | @or_d first second firstMods secondMods firstTyped firstD firstUnit secondTyped =>
      simp only [CoreFragment.WellFormed] at wellFormed
      have firstSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings firstTyped wellFormed.1
      have secondSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings secondTyped wellFormed.2
      simpa [satisfactionCandidates] using
        (CandidatePair.SupportsGeneratedContract.or_d firstSupported firstD
          firstUnit secondSupported)
  | @or_i first second firstType secondType firstTyped secondTyped branch baseEq =>
      simp only [CoreFragment.WellFormed] at wellFormed
      have firstSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings firstTyped wellFormed.1
      have secondSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings secondTyped wellFormed.2
      cases firstType with
      | mk firstBase firstMods =>
          cases secondType with
          | mk secondBase secondMods =>
              change firstBase = secondBase at baseEq
              subst secondBase
              simpa [satisfactionCandidates] using
                (CandidatePair.SupportsGeneratedContract.or_i firstSupported
                  secondSupported branch)
  | @andor first second third firstMods secondType thirdType firstTyped firstD
      firstUnit secondTyped thirdTyped branch baseEq =>
      simp only [CoreFragment.WellFormed] at wellFormed
      have firstSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings firstTyped wellFormed.1
      have secondSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings secondTyped wellFormed.2.1
      have thirdSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings thirdTyped wellFormed.2.2.1
      cases secondType with
      | mk secondBase secondMods =>
          cases thirdType with
          | mk thirdBase thirdMods =>
              change secondBase = thirdBase at baseEq
              subst thirdBase
              simpa [satisfactionCandidates] using
                (CandidatePair.SupportsGeneratedContract.andor firstSupported
                  firstD firstUnit secondSupported thirdSupported branch)
  | @c_wrap child mods childTyped =>
      have childSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings childTyped wellFormed
      simpa [satisfactionCandidates] using
        (CandidatePair.SupportsGeneratedContract.c childSupported)
  | @v_wrap child mods childTyped =>
      have childSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings childTyped wellFormed
      simpa [satisfactionCandidates] using
        (CandidatePair.SupportsGeneratedContract.v childSupported)
  | @a_wrap child mods childTyped =>
      have childSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings childTyped wellFormed
      simpa [satisfactionCandidates] using
        (CandidatePair.SupportsGeneratedContract.a childSupported)
  | @s_wrap child mods childTyped oneArg =>
      have childSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings childTyped wellFormed
      simpa [satisfactionCandidates] using
        (CandidatePair.SupportsGeneratedContract.s childSupported oneArg)
  | @d_wrap child mods childTyped zeroArg =>
      have childSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings childTyped wellFormed
      simpa [satisfactionCandidates] using
        (CandidatePair.SupportsGeneratedContract.d childSupported zeroArg)
  | @j_wrap child mods childTyped nonzero =>
      have childSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings childTyped wellFormed
      simpa [satisfactionCandidates] using
        (CandidatePair.SupportsGeneratedContract.j childSupported nonzero)
  | @n_wrap child mods childTyped =>
      have childSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings childTyped wellFormed
      simpa [satisfactionCandidates] using
        (CandidatePair.SupportsGeneratedContract.n childSupported)
  | @thresh threshold first rest firstMods restTypes firstTyped firstD firstUnit
      restTyped restShape positive atMost =>
      have childrenWellFormed := wellFormed.2.1
      simp only [CoreFragment.allWellFormed] at childrenWellFormed
      have firstSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings firstTyped childrenWellFormed.1
      have restSupported :=
        supportsGeneratedContractList_of_allWellFormed_hasTypeList
          version modeled sound encodings restTyped childrenWellFormed.2
      by_cases valid : candidateThresholdValid threshold (first :: rest).length
      · exact generatedContract_thresh firstSupported firstD firstUnit restSupported
          restShape positive atMost valid.2.2
      · exact generatedContract_thresh_invalid
          (.thresh firstTyped firstD firstUnit restTyped restShape positive atMost)
          valid
  | multi threshold keys positive atMost =>
      exact generatedContract_multi_of_wellFormed wellFormed version modeled
        sound encodings
  | multi_a threshold keys positive atMost =>
      exact generatedContract_multiA_of_wellFormed wellFormed version modeled
        sound encodings

/-- Pointwise list counterpart of
    `supportsGeneratedContract_of_wellFormed_hasType`. -/
theorem supportsGeneratedContractList_of_allWellFormed_hasTypeList
    {scriptCtx : ScriptContext} {fragments : List CoreFragment}
    {types : List MiniType} {env : SatEnv} {flags : ScriptFlags}
    (version : ModeledContextVersion scriptCtx env.txCtx)
    (modeled : ModeledContextFlags scriptCtx flags)
    (sound : env.Sound) (encodings : env.EncodingSound flags)
    (typed : HasTypeList scriptCtx fragments types)
    (wellFormed : CoreFragment.allWellFormed scriptCtx fragments) :
    SupportsGeneratedContractList scriptCtx flags env.txCtx
      (satisfactionCandidatesList fragments env) fragments types := by
  cases typed with
  | nil => exact .nil
  | @cons fragment ty fragments types headTyped tailTyped =>
      simp only [CoreFragment.allWellFormed] at wellFormed
      have headSupported := supportsGeneratedContract_of_wellFormed_hasType
        version modeled sound encodings headTyped wellFormed.1
      have tailSupported :=
        supportsGeneratedContractList_of_allWellFormed_hasTypeList
          version modeled sound encodings tailTyped wellFormed.2
      simpa [satisfactionCandidatesList] using
        (SupportsGeneratedContractList.cons headSupported tailSupported)

end

end LeanMiniscript.Miniscript
