#!/usr/bin/env python3
"""Refresh exact Core/BIP143 vectors embedded in LegacySighashExamples.lean."""
# Official input sources (exact bytes are checksum-pinned below):
# https://raw.githubusercontent.com/bitcoin/bitcoin/9be056a8a72b624dae9623b2f7bded92c2a21c91/src/test/data/sighash.json
# https://raw.githubusercontent.com/bitcoin/bips/master/bip-0143.mediawiki
import argparse
import hashlib
import json
from pathlib import Path
import re

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('core_json', type=Path)
parser.add_argument('bip143', type=Path)
args = parser.parse_args()
if hashlib.sha256(args.core_json.read_bytes()).hexdigest() != '52cf23c2076e7f129c71d5508631d3e5ae3be1b1cb0585c0e23bbb4bb373e924':
    raise SystemExit('Source checksum mismatch; expected SHA-256 52cf23c2076e7f129c71d5508631d3e5ae3be1b1cb0585c0e23bbb4bb373e924')
if hashlib.sha256(args.bip143.read_bytes()).hexdigest() != '62bc71351563e68baeb12643c68355d217953ae9eb6a6e68b2b0323275b6beec':
    raise SystemExit('Source checksum mismatch; expected SHA-256 62bc71351563e68baeb12643c68355d217953ae9eb6a6e68b2b0323275b6beec')
core = json.loads(args.core_json.read_text())[1:]
assert len(core) == 500
text = args.bip143.read_text()

def compact(data, offset):
    size = data[offset]
    offset += 1
    if size < 253:
        return size, offset
    width = {253: 2, 254: 4, 255: 8}[size]
    return int.from_bytes(data[offset:offset + width], 'little'), offset + width

def prevouts(raw):
    data = bytes.fromhex(raw)
    count, pos = compact(data, 4)
    result = []
    for _ in range(count):
        result.append(data[pos:pos + 36])
        pos += 36
        size, pos = compact(data, pos)
        pos += size + 4
    return result

witness = []
for match in re.finditer(r'(?m)^\s+sigHash:\s+([0-9a-f]{64})', text):
    before = text[:match.start()]
    raw = list(re.finditer(r'The following is an unsigned transaction:\s*([0-9a-f]+)', before))[-1][1]
    preimage = bytes.fromhex(list(re.finditer(r'(?:hash )?preimage(?: for [^:\n]+)?:\s*([0-9a-f]+)', before))[-1][1])
    assert hashlib.sha256(hashlib.sha256(preimage).digest()).hexdigest() == match[1]
    size, pos = compact(preimage, 104)
    script = preimage[pos:pos + size].hex()
    amount = int.from_bytes(preimage[pos + size:pos + size + 8], 'little')
    kind = int.from_bytes(preimage[-4:], 'little')
    index = prevouts(raw).index(preimage[68:104])
    witness.append([raw, script, index, amount, kind, match[1]])
assert len(witness) == 13

block = '-- BEGIN GENERATED VECTORS\n'
block += '/-! Core revision 9be056a8a72b624dae9623b2f7bded92c2a21c91, src/test/data/sighash.json.\n'
block += 'Core source SHA-256: ' + hashlib.sha256(args.core_json.read_bytes()).hexdigest() + '.\n'
block += 'Official BIP143 source SHA-256: ' + hashlib.sha256(args.bip143.read_bytes()).hexdigest() + '.\n'
block += 'Generated by scripts/generate_legacy_sighash_fixtures.py. Core display hashes are reversed\n'
block += 'at comparison; BIP143 digests are already in byte order. -/\n'
for name, rows in [('coreVectorJson', core), ('witnessVectorJson', witness)]:
    block += f'private def {name} : String := r#"\n[\n'
    block += ',\n'.join('  ' + json.dumps(row, separators=(',', ':')) for row in rows)
    block += '\n]\n"#\n'
block += '-- END GENERATED VECTORS'
out = Path(__file__).resolve().parent.parent / 'LeanMiniscript/Bitcoin/LegacySighashExamples.lean'
content = out.read_text()
if '-- VECTOR_DATA' in content:
    content = content.replace('-- VECTOR_DATA', block)
else:
    content = re.sub(r'-- BEGIN GENERATED VECTORS.*?-- END GENERATED VECTORS', lambda _: block, content, flags=re.S)
out.write_text(content)
print(f'Wrote {len(core)} Core and {len(witness)} BIP143 vectors.')
