#!/usr/bin/env python3
"""Extract BIP143 signatures and derive explicit Core lax-DER/key compatibility cases."""
# Official input sources (exact bytes are checksum-pinned below):
# https://raw.githubusercontent.com/bitcoin/bips/master/bip-0143.mediawiki
import argparse
import hashlib
from pathlib import Path
import re

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('bip143', type=Path)
args = parser.parse_args()
if hashlib.sha256(args.bip143.read_bytes()).hexdigest() != '62bc71351563e68baeb12643c68355d217953ae9eb6a6e68b2b0323275b6beec':
    raise SystemExit('Source checksum mismatch; expected SHA-256 62bc71351563e68baeb12643c68355d217953ae9eb6a6e68b2b0323275b6beec')
text = args.bip143.read_text()
rows = []
for match in re.finditer(r'(?m)^\s+sigHash:\s+([0-9a-f]{64})', text):
    after = text[match.end():]
    signature = re.search(r'(?m)^\s+signature:\s+([0-9a-f ]+)', after)
    assert signature
    signature_hex = signature[1].replace(' ', '')
    keys = list(re.finditer(r'(?m)^\s+(?:public key|pubkey)\s*:\s+([0-9a-f]+)', text[:match.start()]))
    nearby = re.search(r'(?m)^\s+(?:public key|pubkey)\s*:\s+([0-9a-f]+)', after[:signature.end() + 100])
    key = nearby[1] if nearby else keys[-1][1]
    rows.append((signature_hex[:-2], key, match[1]))
assert len(rows) == 13

# Transform the first published signature, preserving its R/S values.
sig, key, digest = rows[0]
data = bytes.fromhex(sig)
r = data[4:4 + data[3]]
s = data[6 + data[3]:]
assert len(s) == data[5 + data[3]]
field = 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f
order = 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141
x = int(key[2:], 16)
y = pow((x ** 3 + 7) % field, (field + 1) // 4, field)
if y % 2 != int(key[:2], 16) % 2:
    y = field - y
uncompressed = '04' + f'{x:064x}{y:064x}'
hybrid = f'{6 + y % 2:02x}' + uncompressed[2:]

def integer(value):
    raw = value.to_bytes((value.bit_length() + 7) // 8 or 1, 'big')
    if raw[0] & 128:
        raw = b'\0' + raw
    return bytes([2, len(raw)]) + raw

high_s_body = integer(int.from_bytes(r, 'big')) + integer(order - int.from_bytes(s, 'big'))
compatibility = [(sig, uncompressed, digest), (sig, hybrid, digest),
    ((bytes([48, len(high_s_body)]) + high_s_body).hex(), key, digest),
    ((b'\x30\0' + data[2:] + b'\xff\x01').hex(), key, digest),
    ((b'\x30\x83\xff\xff\xff' + data[2:]).hex(), key, digest),
    ((b'\x30\0\x02\x84\0\0\0' + bytes([len(r)]) + r + b'\x02\x83\0\0' + bytes([len(s)]) + s).hex(), key, digest),
    ((b'\x30\0\x02' + bytes([len(r)+2]) + b'\0\0' + r + b'\x02' + bytes([len(s)+2]) + b'\0\0' + s).hex(), key, digest)]
block = '-- BEGIN GENERATED VECTORS\n'
block += '/-! Official BIP143 SHA-256: ' + hashlib.sha256(args.bip143.read_bytes()).hexdigest() + '.\n'
block += 'Thirteen published ECDSA signatures, excluding their Script hash-type bytes.\n'
block += 'Derived cases cover uncompressed/hybrid keys, high S, ignored sequence lengths,\n'
block += 'trailing bytes, long descriptors and excessive scalar padding.\n'
block += 'Generated by scripts/generate_ecdsa_fixtures.py. -/\n'
for name, vectors in [('bip143Signatures', rows), ('compatibilitySignatures', compatibility)]:
    block += f'private def {name} : Array (String × String × String) := #[\n'
    block += ',\n'.join(f'  ("{sig}", "{key}", "{digest}")' for sig, key, digest in vectors)
    block += ']\n'
block += '-- END GENERATED VECTORS'
out = Path(__file__).resolve().parent.parent / 'LeanMiniscript/Bitcoin/ECDSAExamples.lean'
out.write_text(re.sub(r'-- BEGIN GENERATED VECTORS.*?-- END GENERATED VECTORS', lambda _: block, out.read_text(), flags=re.S))
print(f'Wrote {len(rows)} BIP143 signatures and {len(compatibility)} derived cases.')
