#!/usr/bin/env python3
"""Refresh selected Core P2PK signatures and independently serialized fixture transactions."""
# Official input sources (exact bytes are checksum-pinned below):
# https://raw.githubusercontent.com/bitcoin/bitcoin/9be056a8a72b624dae9623b2f7bded92c2a21c91/src/test/data/script_tests.json
import argparse
import hashlib
import json
from pathlib import Path
import re

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('script_tests', type=Path)
args = parser.parse_args()
source = args.script_tests.read_bytes()
if hashlib.sha256(source).hexdigest() != 'bc23cb1dfa760d50042f534da23cbbe4b6fbb03d7def0b64f8de049453d6ead5':
    raise SystemExit('Source checksum mismatch; expected SHA-256 bc23cb1dfa760d50042f534da23cbbe4b6fbb03d7def0b64f8de049453d6ead5')
rows = json.loads(source)
indices = [1028, 1029, 1032, 1033, 1043, 1045, 1047, 1049, 1080, 1082, 1084, 1090, 1095, 1097]

def script(text):
    return b''.join(bytes.fromhex(token[2:]) if token.startswith('0x') else
                   {'CHECKSIG': b'\xac', 'NOT': b'\x91'}[token] for token in text.split())

block = '-- BEGIN GENERATED VECTORS\n'
block += '/-! Core revision 9be056a8a72b624dae9623b2f7bded92c2a21c91, script_tests.json.\n'
block += 'Source SHA-256: ' + hashlib.sha256(source).hexdigest() + '.\n'
block += 'Indices below include upstream comment rows; expected values concern CHECKSIG\n'
block += 'before an optional NOT. Strict Script encoding flags remain outside this test.\n'
block += 'Generated by scripts/generate_core_fixture_transaction_examples.py. -/\n'
block += 'private def coreSignatures : Array (String × String × Bool) := #[\n'
vectors = []
for index in indices:
    sig, pubkey, flags, result, description = rows[index]
    assert flags == ''
    expected = (result == 'OK') != pubkey.endswith(' NOT')
    vectors.append(f'  -- Upstream row {index}: {description}.\n  ("{script(sig).hex()}", "{script(pubkey).hex()}", {str(expected).lower()})')
block += ',\n'.join(vectors) + ']\n'

# Independent stdlib serialization of Core's two one-input, one-output builders.
amount = (42).to_bytes(8, 'little')
credit = bytes.fromhex('0100000001') + bytes(32) + bytes.fromhex('ffffffff020000ffffffff01') + amount + bytes.fromhex('015100000000')
txid = hashlib.sha256(hashlib.sha256(credit).digest()).digest()
spend = bytes.fromhex('0100000001') + txid + bytes.fromhex('00000000020155ffffffff01') + amount + bytes.fromhex('0000000000')
block += f'private def expectedCredit : String := "{credit.hex()}"\n'
block += f'private def expectedSpend : String := "{spend.hex()}"\n'
block += '-- END GENERATED VECTORS'
out = Path(__file__).resolve().parent.parent / 'LeanMiniscript/Extraction/CoreFixtureTransactionExamples.lean'
out.write_text(re.sub(r'-- BEGIN GENERATED VECTORS.*?-- END GENERATED VECTORS', lambda _: block, out.read_text(), flags=re.S))
print(f'Wrote {len(indices)} exact Core signature cases and 2 transaction serializations.')
